### ISSUE TITLE
Win+Space is broken

### ISSUE THREAD

**Issue by Felix14-v2** [Evengard/ep_extra_evengard.win11disableinputswitchwindow#2]
Alt+Shift is working like a charm, but now Win+Space just does nothing. If it is possible, it would be great to still have this shortcut available.

**Comment by Evengard** [comment]
I think I did that partly by accident, partly intentional. I'll try to look into getting it back, but it may be not possible to avoid the popup specifically for win space.

**Comment by Evengard** [comment]
Try this one https://github.com/Evengard/ep_extra_evengard.win11disableinputswitchwindow/releases/tag/v0.0.2

As I said I did not manage removing the modal dialog for Win+Space because it seems to be tied into it a lot more and without it it acted kind of erratically

**Comment by Felix14-v2** [comment]
Thanks a lot, the issue seems to be gone!

> I did not manage removing the modal dialog for Win+Space

Actually Win+Space dialog is only shown if you hold down the space button long enough (≈ half of a second in my case), so the pop-up menu isn't a problem in normal use.
